# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Package

on:
  release:
    types: [created]


  build:
    runs-on:
    steps:
      - uses:
      
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      
      - uses: añ
        with:
          node-version: 16
          registry-url
      - run: npm ci
      - run: npm publish
        env:
          
